version: '3.9'
services:
  app:
    image: jungdae/inforest-app
    ports:
      - "50051:50051"
    networks:
      - inforest_network
    env_file:
      - config/.env
      - config/.env_neo4j
      - config/.env_supabase
      - config/.env_redis
    depends_on:
      - db

  ai-app:
    image: jungdae/inforest-ai-service 
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - config/.env_google
      - config/.env_redis
      - config/.env_neo4j
    networks:
      - inforest_network
  
  worker:
    image: jungdae/inforest-ai-service
    command: python3 worker.py
    networks:
      - inforest_network
    depends_on:
      - redis
    env_file:
      - config/.env_google
      - config/.env_redis
      - config/.env_neo4j

  db:
    image: neo4j:latest
    env_file:
      - config/.env_neo4j_db
    networks:
      - inforest_network
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - db_data:/data
  redis:
    image: jungdae/redis-store:latest
    networks:
      - inforest_network
    ports:
      - "6379:6379"
    

volumes:
  db_data: {}
networks:
  inforest_network:
    driver: bridge